spring:
  application:
    name: document-service

server:
  port: 12345

spring:
  data:
    mongodb:
      host: localhost
      port: 1003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
