spring:
  application:
    name: user-service

server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 1001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
